# Generated by Django 4.2.14 on 2024-07-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='description',
            field=models.TextField(db_column='description', null=True),
        ),
    ]
